supported_languages: 
- en
- fr
- nl

default_score_threshold: 0.5

nlp_configuration:
  nlp_engine_name: spacy
  models:
  -
    lang_code: en
    model_name: en_core_web_sm
  -
    lang_code: fr
    model_name: fr_core_news_md
  -
    lang_code: nl
    model_name: nl_core_news_sm
  
  ner_model_configuration:
    labels_to_ignore:
    - PER
    - PERSON
    - LOC
    - LOCATION
    - ORG
    model_to_presidio_entity_mapping:
      PER: PERSON
      PERSON: PERSON
      LOC: LOCATION
      LOCATION: LOCATION
      GPE: LOCATION
      ORG: ORGANIZATION
      DATE: DATE_TIME
      TIME: DATE_TIME
      NORP: NRP
      # MISC: SENSITIVE

    low_confidence_score_multiplier: 0.5

recognizer_registry:
  global_regex_flags: 26

  recognizers: 

  - name: 'GreetRecognizerEn'
    supported_language: 'en'
    supported_entity: 'GREET'
    deny_list: ['Hello']
    deny_list_score: 1

  - name: 'GreetRecognizerFr'
    supported_language: 'fr'
    supported_entity: 'GREET'
    deny_list: ['Bonjour']
    deny_list_score: 1

  - name: 'HealthRecognizerEn'
    supported_language: 'en'
    supported_entity: 'HEALTH'
    deny_list: [diabetes, asthma, hypertension, Allergie, retard, mentale, Amlodipine, handicapé]
    deny_list_score: 1

  - name: 'HealthRecognizerFr'
    supported_language: 'fr'
    supported_entity: 'HEALTH'
    deny_list: [diabète, hypertension, Allergie, retard, mentale, Amlodipine, handicapé]
    deny_list_score: 1

