nlp_engine_name: spacy
models:
  -
    lang_code: en
    model_name: en_core_web_lg
  -
    lang_code: es
    model_name: es_core_news_md 
    
ner_model_configuration:
labels_to_ignore:
- O
model_to_presidio_entity_mapping:
    PER: PERSON
    LOC: LOCATION
    ORG: ORGANIZATION
    AGE: AGE
    ID: ID
    DATE: DATE_TIME
low_confidence_score_multiplier: 0.4
low_score_entity_names:
- ID
- ORG